# Generated by Django 5.1.1 on 2024-09-18 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atelier', '0001_initial'),
        ('fournisseur', '0001_initial'),
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceDetachee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_piecedetache', models.CharField(max_length=100, verbose_name='Nom de la pièce détachée')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_achat', models.DateField(blank=True, null=True, verbose_name="Date d'achat")),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('reference_fabricant', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference fabricant')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('stock_min', models.PositiveIntegerField(verbose_name='Stock minimum')),
                ('stock_max', models.PositiveIntegerField(verbose_name='Stock maximum')),
                ('lot_de_reapprovisionnement', models.PositiveSmallIntegerField(verbose_name='Lot de réapprovisionnement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Date de suppression')),
                ('emplacement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atelier.atelier', verbose_name='Emplacement')),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fournisseur.fournisseur', verbose_name='Fournisseur')),
                ('modele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='machine.modele', verbose_name='Modele')),
            ],
        ),
    ]
