--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: maintenance_atelier; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.maintenance_atelier (
    id bigint NOT NULL,
    nom_atelier character varying(50) NOT NULL,
    date_creation timestamp with time zone,
    deleted_at date,
    endroit_id bigint,
    responsable_id bigint
);


ALTER TABLE public.maintenance_atelier OWNER TO postgres;

--
-- Name: maintenance_atelier_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.maintenance_atelier ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maintenance_atelier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maintenance_chaine; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.maintenance_chaine (
    id bigint NOT NULL,
    nom_chaine character varying(50) NOT NULL,
    date_creation timestamp with time zone,
    deleted_at date,
    atelier_id bigint
);


ALTER TABLE public.maintenance_chaine OWNER TO postgres;

--
-- Name: maintenance_chaine_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.maintenance_chaine ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maintenance_chaine_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maintenance_endroit; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.maintenance_endroit (
    id bigint NOT NULL,
    nom_endroit character varying(50) NOT NULL,
    date_creation timestamp with time zone,
    deleted_at date
);


ALTER TABLE public.maintenance_endroit OWNER TO postgres;

--
-- Name: maintenance_endroit_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.maintenance_endroit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maintenance_endroit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maintenance_fournisseur; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.maintenance_fournisseur (
    id bigint NOT NULL,
    nom_fournisseur character varying(50) NOT NULL,
    email character varying(254),
    telephone character varying(15),
    date_creation timestamp with time zone,
    deleted_at date
);


ALTER TABLE public.maintenance_fournisseur OWNER TO postgres;

--
-- Name: maintenance_fournisseur_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.maintenance_fournisseur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maintenance_fournisseur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maintenance_historiquemouvementmachine; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.maintenance_historiquemouvementmachine (
    id bigint NOT NULL,
    date_creation timestamp with time zone,
    deleted_at date,
    atelier_id bigint,
    chaine_id bigint,
    machine_id bigint
);


ALTER TABLE public.maintenance_historiquemouvementmachine OWNER TO postgres;

--
-- Name: maintenance_historiquemouvementmachine_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.maintenance_historiquemouvementmachine ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maintenance_historiquemouvementmachine_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maintenance_machine; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.maintenance_machine (
    id bigint NOT NULL,
    numero_de_serie character varying(100) NOT NULL,
    numero_de_moteur character varying(50),
    date_mis_en_place date,
    status_id bigint NOT NULL,
    description text,
    image character varying(100),
    reference_fabricant character varying(50),
    date_creation timestamp with time zone,
    deleted_at date,
    fournisseur_id bigint,
    marque_id bigint,
    nom_machine character varying(50) NOT NULL,
    type_id bigint,
    date_acquisition date,
    date_hors_service date,
    atelier_id bigint,
    chaine_id bigint
);


ALTER TABLE public.maintenance_machine OWNER TO postgres;

--
-- Name: maintenance_machine_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.maintenance_machine ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maintenance_machine_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maintenance_machine_pieces_detachees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.maintenance_machine_pieces_detachees (
    id bigint NOT NULL,
    machine_id bigint NOT NULL,
    piecedetachee_id bigint NOT NULL
);


ALTER TABLE public.maintenance_machine_pieces_detachees OWNER TO postgres;

--
-- Name: maintenance_machine_pieces_detachees_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.maintenance_machine_pieces_detachees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maintenance_machine_pieces_detachees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maintenance_machinerelation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.maintenance_machinerelation (
    id bigint NOT NULL,
    quantite integer,
    machine_liee_id bigint,
    machine_principale_id bigint,
    CONSTRAINT maintenance_machinerelation_quantite_check CHECK ((quantite >= 0))
);


ALTER TABLE public.maintenance_machinerelation OWNER TO postgres;

--
-- Name: maintenance_machinerelation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.maintenance_machinerelation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maintenance_machinerelation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maintenance_marque; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.maintenance_marque (
    id bigint NOT NULL,
    nom_marque character varying(50) NOT NULL,
    date_creation timestamp with time zone,
    deleted_at date
);


ALTER TABLE public.maintenance_marque OWNER TO postgres;

--
-- Name: maintenance_marque_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.maintenance_marque ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maintenance_marque_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maintenance_modele; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.maintenance_modele (
    id bigint NOT NULL,
    nom_modele character varying(50) NOT NULL,
    date_creation timestamp with time zone,
    deleted_at date
);


ALTER TABLE public.maintenance_modele OWNER TO postgres;

--
-- Name: maintenance_modele_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.maintenance_modele ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maintenance_modele_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maintenance_nommachine; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.maintenance_nommachine (
    id bigint NOT NULL,
    nom_machine character varying(50) NOT NULL,
    date_creation timestamp with time zone,
    deleted_at date
);


ALTER TABLE public.maintenance_nommachine OWNER TO postgres;

--
-- Name: maintenance_nommachine_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.maintenance_nommachine ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maintenance_nommachine_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maintenance_piecedetachee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.maintenance_piecedetachee (
    id bigint NOT NULL,
    nom_piecedetache character varying(100) NOT NULL,
    description text,
    date_achat timestamp with time zone,
    prix_unitaire numeric(10,2) NOT NULL,
    reference_fabricant character varying(50),
    image character varying(100),
    stock_min integer NOT NULL,
    stock_max integer,
    lot_de_reapprovisionnement smallint,
    date_creation timestamp with time zone,
    deleted_at date,
    emplacement_id bigint,
    fournisseur_id bigint,
    modele_id bigint,
    quantite integer NOT NULL,
    CONSTRAINT maintenance_piecedetachee_lot_de_reapprovisionnement_check CHECK ((lot_de_reapprovisionnement >= 0)),
    CONSTRAINT maintenance_piecedetachee_quantite_check CHECK ((quantite >= 0)),
    CONSTRAINT maintenance_piecedetachee_stock_max_check CHECK ((stock_max >= 0)),
    CONSTRAINT maintenance_piecedetachee_stock_min_check CHECK ((stock_min >= 0))
);


ALTER TABLE public.maintenance_piecedetachee OWNER TO postgres;

--
-- Name: maintenance_piecedetachee_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.maintenance_piecedetachee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maintenance_piecedetachee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maintenance_responsable; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.maintenance_responsable (
    id bigint NOT NULL,
    nom_responsable character varying(50) NOT NULL,
    email character varying(254),
    telephone character varying(15),
    photo character varying(100),
    date_creation timestamp with time zone,
    deleted_at date
);


ALTER TABLE public.maintenance_responsable OWNER TO postgres;

--
-- Name: maintenance_responsable_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.maintenance_responsable ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maintenance_responsable_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maintenance_status; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.maintenance_status (
    id bigint NOT NULL,
    nom_status character varying(50) NOT NULL,
    date_creation timestamp with time zone,
    deleted_at date,
    couleur character varying(10)
);


ALTER TABLE public.maintenance_status OWNER TO postgres;

--
-- Name: maintenance_status_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.maintenance_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maintenance_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maintenance_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.maintenance_type (
    id bigint NOT NULL,
    nom_type character varying(50) NOT NULL,
    date_creation timestamp with time zone,
    deleted_at date
);


ALTER TABLE public.maintenance_type OWNER TO postgres;

--
-- Name: maintenance_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.maintenance_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maintenance_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: utilisateur_utilisateur; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.utilisateur_utilisateur (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone NOT NULL,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(50),
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    role character varying(50) NOT NULL,
    is_active boolean NOT NULL
);


ALTER TABLE public.utilisateur_utilisateur OWNER TO postgres;

--
-- Name: utilisateur_utilisateur_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.utilisateur_utilisateur_groups (
    id bigint NOT NULL,
    utilisateur_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.utilisateur_utilisateur_groups OWNER TO postgres;

--
-- Name: utilisateur_utilisateur_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.utilisateur_utilisateur_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.utilisateur_utilisateur_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: utilisateur_utilisateur_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.utilisateur_utilisateur ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.utilisateur_utilisateur_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: utilisateur_utilisateur_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.utilisateur_utilisateur_user_permissions (
    id bigint NOT NULL,
    utilisateur_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.utilisateur_utilisateur_user_permissions OWNER TO postgres;

--
-- Name: utilisateur_utilisateur_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.utilisateur_utilisateur_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.utilisateur_utilisateur_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: maintenance_atelier maintenance_atelier_nom_atelier_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_atelier
    ADD CONSTRAINT maintenance_atelier_nom_atelier_key UNIQUE (nom_atelier);


--
-- Name: maintenance_atelier maintenance_atelier_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_atelier
    ADD CONSTRAINT maintenance_atelier_pkey PRIMARY KEY (id);


--
-- Name: maintenance_chaine maintenance_chaine_nom_chaine_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_chaine
    ADD CONSTRAINT maintenance_chaine_nom_chaine_key UNIQUE (nom_chaine);


--
-- Name: maintenance_chaine maintenance_chaine_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_chaine
    ADD CONSTRAINT maintenance_chaine_pkey PRIMARY KEY (id);


--
-- Name: maintenance_endroit maintenance_endroit_nom_endroit_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_endroit
    ADD CONSTRAINT maintenance_endroit_nom_endroit_key UNIQUE (nom_endroit);


--
-- Name: maintenance_endroit maintenance_endroit_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_endroit
    ADD CONSTRAINT maintenance_endroit_pkey PRIMARY KEY (id);


--
-- Name: maintenance_fournisseur maintenance_fournisseur_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_fournisseur
    ADD CONSTRAINT maintenance_fournisseur_email_key UNIQUE (email);


--
-- Name: maintenance_fournisseur maintenance_fournisseur_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_fournisseur
    ADD CONSTRAINT maintenance_fournisseur_pkey PRIMARY KEY (id);


--
-- Name: maintenance_historiquemouvementmachine maintenance_historiquemouvementmachine_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_historiquemouvementmachine
    ADD CONSTRAINT maintenance_historiquemouvementmachine_pkey PRIMARY KEY (id);


--
-- Name: maintenance_machine maintenance_machine_numero_de_serie_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_machine
    ADD CONSTRAINT maintenance_machine_numero_de_serie_key UNIQUE (numero_de_serie);


--
-- Name: maintenance_machine_pieces_detachees maintenance_machine_piec_machine_id_piecedetachee_be1092d0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_machine_pieces_detachees
    ADD CONSTRAINT maintenance_machine_piec_machine_id_piecedetachee_be1092d0_uniq UNIQUE (machine_id, piecedetachee_id);


--
-- Name: maintenance_machine_pieces_detachees maintenance_machine_pieces_detachees_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_machine_pieces_detachees
    ADD CONSTRAINT maintenance_machine_pieces_detachees_pkey PRIMARY KEY (id);


--
-- Name: maintenance_machine maintenance_machine_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_machine
    ADD CONSTRAINT maintenance_machine_pkey PRIMARY KEY (id);


--
-- Name: maintenance_machinerelation maintenance_machinerelation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_machinerelation
    ADD CONSTRAINT maintenance_machinerelation_pkey PRIMARY KEY (id);


--
-- Name: maintenance_marque maintenance_marque_nom_marque_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_marque
    ADD CONSTRAINT maintenance_marque_nom_marque_key UNIQUE (nom_marque);


--
-- Name: maintenance_marque maintenance_marque_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_marque
    ADD CONSTRAINT maintenance_marque_pkey PRIMARY KEY (id);


--
-- Name: maintenance_modele maintenance_modele_nom_modele_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_modele
    ADD CONSTRAINT maintenance_modele_nom_modele_key UNIQUE (nom_modele);


--
-- Name: maintenance_modele maintenance_modele_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_modele
    ADD CONSTRAINT maintenance_modele_pkey PRIMARY KEY (id);


--
-- Name: maintenance_nommachine maintenance_nommachine_nom_machine_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_nommachine
    ADD CONSTRAINT maintenance_nommachine_nom_machine_key UNIQUE (nom_machine);


--
-- Name: maintenance_nommachine maintenance_nommachine_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_nommachine
    ADD CONSTRAINT maintenance_nommachine_pkey PRIMARY KEY (id);


--
-- Name: maintenance_piecedetachee maintenance_piecedetachee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_piecedetachee
    ADD CONSTRAINT maintenance_piecedetachee_pkey PRIMARY KEY (id);


--
-- Name: maintenance_responsable maintenance_responsable_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_responsable
    ADD CONSTRAINT maintenance_responsable_email_key UNIQUE (email);


--
-- Name: maintenance_responsable maintenance_responsable_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_responsable
    ADD CONSTRAINT maintenance_responsable_pkey PRIMARY KEY (id);


--
-- Name: maintenance_status maintenance_status_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_status
    ADD CONSTRAINT maintenance_status_pkey PRIMARY KEY (id);


--
-- Name: maintenance_type maintenance_type_nom_type_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_type
    ADD CONSTRAINT maintenance_type_nom_type_key UNIQUE (nom_type);


--
-- Name: maintenance_type maintenance_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_type
    ADD CONSTRAINT maintenance_type_pkey PRIMARY KEY (id);


--
-- Name: utilisateur_utilisateur_groups utilisateur_utilisateur__utilisateur_id_group_id_f6666e2f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utilisateur_utilisateur_groups
    ADD CONSTRAINT utilisateur_utilisateur__utilisateur_id_group_id_f6666e2f_uniq UNIQUE (utilisateur_id, group_id);


--
-- Name: utilisateur_utilisateur_user_permissions utilisateur_utilisateur__utilisateur_id_permissio_500c8d2f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utilisateur_utilisateur_user_permissions
    ADD CONSTRAINT utilisateur_utilisateur__utilisateur_id_permissio_500c8d2f_uniq UNIQUE (utilisateur_id, permission_id);


--
-- Name: utilisateur_utilisateur utilisateur_utilisateur_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utilisateur_utilisateur
    ADD CONSTRAINT utilisateur_utilisateur_email_key UNIQUE (email);


--
-- Name: utilisateur_utilisateur_groups utilisateur_utilisateur_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utilisateur_utilisateur_groups
    ADD CONSTRAINT utilisateur_utilisateur_groups_pkey PRIMARY KEY (id);


--
-- Name: utilisateur_utilisateur utilisateur_utilisateur_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utilisateur_utilisateur
    ADD CONSTRAINT utilisateur_utilisateur_pkey PRIMARY KEY (id);


--
-- Name: utilisateur_utilisateur_user_permissions utilisateur_utilisateur_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utilisateur_utilisateur_user_permissions
    ADD CONSTRAINT utilisateur_utilisateur_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: utilisateur_utilisateur utilisateur_utilisateur_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utilisateur_utilisateur
    ADD CONSTRAINT utilisateur_utilisateur_username_key UNIQUE (username);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: maintenance_atelier_endroit_id_db2087a2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_atelier_endroit_id_db2087a2 ON public.maintenance_atelier USING btree (endroit_id);


--
-- Name: maintenance_atelier_nom_atelier_0db65890_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_atelier_nom_atelier_0db65890_like ON public.maintenance_atelier USING btree (nom_atelier varchar_pattern_ops);


--
-- Name: maintenance_atelier_responsable_id_bb70148d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_atelier_responsable_id_bb70148d ON public.maintenance_atelier USING btree (responsable_id);


--
-- Name: maintenance_chaine_atelier_id_ea9e2842; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_chaine_atelier_id_ea9e2842 ON public.maintenance_chaine USING btree (atelier_id);


--
-- Name: maintenance_chaine_nom_chaine_e4ad9971_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_chaine_nom_chaine_e4ad9971_like ON public.maintenance_chaine USING btree (nom_chaine varchar_pattern_ops);


--
-- Name: maintenance_endroit_nom_endroit_02b35266_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_endroit_nom_endroit_02b35266_like ON public.maintenance_endroit USING btree (nom_endroit varchar_pattern_ops);


--
-- Name: maintenance_fournisseur_email_850b14c2_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_fournisseur_email_850b14c2_like ON public.maintenance_fournisseur USING btree (email varchar_pattern_ops);


--
-- Name: maintenance_historiquemouvementmachine_atelier_id_0f8b9156; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_historiquemouvementmachine_atelier_id_0f8b9156 ON public.maintenance_historiquemouvementmachine USING btree (atelier_id);


--
-- Name: maintenance_historiquemouvementmachine_chaine_id_afb33a79; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_historiquemouvementmachine_chaine_id_afb33a79 ON public.maintenance_historiquemouvementmachine USING btree (chaine_id);


--
-- Name: maintenance_historiquemouvementmachine_machine_id_aea951f2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_historiquemouvementmachine_machine_id_aea951f2 ON public.maintenance_historiquemouvementmachine USING btree (machine_id);


--
-- Name: maintenance_machine_atelier_id_0e888470; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_machine_atelier_id_0e888470 ON public.maintenance_machine USING btree (atelier_id);


--
-- Name: maintenance_machine_chaine_id_ec63e3de; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_machine_chaine_id_ec63e3de ON public.maintenance_machine USING btree (chaine_id);


--
-- Name: maintenance_machine_fournisseur_id_9065494e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_machine_fournisseur_id_9065494e ON public.maintenance_machine USING btree (fournisseur_id);


--
-- Name: maintenance_machine_marque_id_d724f20b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_machine_marque_id_d724f20b ON public.maintenance_machine USING btree (marque_id);


--
-- Name: maintenance_machine_numero_de_serie_58268240_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_machine_numero_de_serie_58268240_like ON public.maintenance_machine USING btree (numero_de_serie varchar_pattern_ops);


--
-- Name: maintenance_machine_pieces_detachees_machine_id_68344e6e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_machine_pieces_detachees_machine_id_68344e6e ON public.maintenance_machine_pieces_detachees USING btree (machine_id);


--
-- Name: maintenance_machine_pieces_detachees_piecedetachee_id_e6d0fc9d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_machine_pieces_detachees_piecedetachee_id_e6d0fc9d ON public.maintenance_machine_pieces_detachees USING btree (piecedetachee_id);


--
-- Name: maintenance_machine_status_id_f6a44e07; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_machine_status_id_f6a44e07 ON public.maintenance_machine USING btree (status_id);


--
-- Name: maintenance_machine_type_id_b717a9b6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_machine_type_id_b717a9b6 ON public.maintenance_machine USING btree (type_id);


--
-- Name: maintenance_machinerelation_machine_liee_id_59c7d550; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_machinerelation_machine_liee_id_59c7d550 ON public.maintenance_machinerelation USING btree (machine_liee_id);


--
-- Name: maintenance_machinerelation_machine_principale_id_7201a985; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_machinerelation_machine_principale_id_7201a985 ON public.maintenance_machinerelation USING btree (machine_principale_id);


--
-- Name: maintenance_marque_nom_marque_04d12be4_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_marque_nom_marque_04d12be4_like ON public.maintenance_marque USING btree (nom_marque varchar_pattern_ops);


--
-- Name: maintenance_modele_nom_modele_6b036d06_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_modele_nom_modele_6b036d06_like ON public.maintenance_modele USING btree (nom_modele varchar_pattern_ops);


--
-- Name: maintenance_nommachine_nom_machine_c3d860fc_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_nommachine_nom_machine_c3d860fc_like ON public.maintenance_nommachine USING btree (nom_machine varchar_pattern_ops);


--
-- Name: maintenance_piecedetachee_emplacement_id_7d650eaa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_piecedetachee_emplacement_id_7d650eaa ON public.maintenance_piecedetachee USING btree (emplacement_id);


--
-- Name: maintenance_piecedetachee_fournisseur_id_9595b99f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_piecedetachee_fournisseur_id_9595b99f ON public.maintenance_piecedetachee USING btree (fournisseur_id);


--
-- Name: maintenance_piecedetachee_modele_id_9a43b09f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_piecedetachee_modele_id_9a43b09f ON public.maintenance_piecedetachee USING btree (modele_id);


--
-- Name: maintenance_responsable_email_51194ba1_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_responsable_email_51194ba1_like ON public.maintenance_responsable USING btree (email varchar_pattern_ops);


--
-- Name: maintenance_type_nom_type_e2d80cbe_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX maintenance_type_nom_type_e2d80cbe_like ON public.maintenance_type USING btree (nom_type varchar_pattern_ops);


--
-- Name: utilisateur_utilisateur_email_a3f90552_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX utilisateur_utilisateur_email_a3f90552_like ON public.utilisateur_utilisateur USING btree (email varchar_pattern_ops);


--
-- Name: utilisateur_utilisateur_groups_group_id_73c9927f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX utilisateur_utilisateur_groups_group_id_73c9927f ON public.utilisateur_utilisateur_groups USING btree (group_id);


--
-- Name: utilisateur_utilisateur_groups_utilisateur_id_7f906dff; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX utilisateur_utilisateur_groups_utilisateur_id_7f906dff ON public.utilisateur_utilisateur_groups USING btree (utilisateur_id);


--
-- Name: utilisateur_utilisateur_us_utilisateur_id_c5dd5b38; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX utilisateur_utilisateur_us_utilisateur_id_c5dd5b38 ON public.utilisateur_utilisateur_user_permissions USING btree (utilisateur_id);


--
-- Name: utilisateur_utilisateur_user_permissions_permission_id_cadf1c64; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX utilisateur_utilisateur_user_permissions_permission_id_cadf1c64 ON public.utilisateur_utilisateur_user_permissions USING btree (permission_id);


--
-- Name: utilisateur_utilisateur_username_6ea28165_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX utilisateur_utilisateur_username_6ea28165_like ON public.utilisateur_utilisateur USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_utilisateur_utilisateur_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_utilisateur_utilisateur_id FOREIGN KEY (user_id) REFERENCES public.utilisateur_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: maintenance_atelier maintenance_atelier_endroit_id_db2087a2_fk_maintenan; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_atelier
    ADD CONSTRAINT maintenance_atelier_endroit_id_db2087a2_fk_maintenan FOREIGN KEY (endroit_id) REFERENCES public.maintenance_endroit(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: maintenance_atelier maintenance_atelier_responsable_id_bb70148d_fk_maintenan; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_atelier
    ADD CONSTRAINT maintenance_atelier_responsable_id_bb70148d_fk_maintenan FOREIGN KEY (responsable_id) REFERENCES public.maintenance_responsable(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: maintenance_chaine maintenance_chaine_atelier_id_ea9e2842_fk_maintenan; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_chaine
    ADD CONSTRAINT maintenance_chaine_atelier_id_ea9e2842_fk_maintenan FOREIGN KEY (atelier_id) REFERENCES public.maintenance_atelier(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: maintenance_historiquemouvementmachine maintenance_historiq_atelier_id_0f8b9156_fk_maintenan; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_historiquemouvementmachine
    ADD CONSTRAINT maintenance_historiq_atelier_id_0f8b9156_fk_maintenan FOREIGN KEY (atelier_id) REFERENCES public.maintenance_atelier(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: maintenance_historiquemouvementmachine maintenance_historiq_chaine_id_afb33a79_fk_maintenan; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_historiquemouvementmachine
    ADD CONSTRAINT maintenance_historiq_chaine_id_afb33a79_fk_maintenan FOREIGN KEY (chaine_id) REFERENCES public.maintenance_chaine(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: maintenance_historiquemouvementmachine maintenance_historiq_machine_id_aea951f2_fk_maintenan; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_historiquemouvementmachine
    ADD CONSTRAINT maintenance_historiq_machine_id_aea951f2_fk_maintenan FOREIGN KEY (machine_id) REFERENCES public.maintenance_machine(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: maintenance_machine_pieces_detachees maintenance_machine__machine_id_68344e6e_fk_maintenan; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_machine_pieces_detachees
    ADD CONSTRAINT maintenance_machine__machine_id_68344e6e_fk_maintenan FOREIGN KEY (machine_id) REFERENCES public.maintenance_machine(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: maintenance_machine_pieces_detachees maintenance_machine__piecedetachee_id_e6d0fc9d_fk_maintenan; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_machine_pieces_detachees
    ADD CONSTRAINT maintenance_machine__piecedetachee_id_e6d0fc9d_fk_maintenan FOREIGN KEY (piecedetachee_id) REFERENCES public.maintenance_piecedetachee(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: maintenance_machine maintenance_machine_atelier_id_0e888470_fk_maintenan; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_machine
    ADD CONSTRAINT maintenance_machine_atelier_id_0e888470_fk_maintenan FOREIGN KEY (atelier_id) REFERENCES public.maintenance_atelier(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: maintenance_machine maintenance_machine_chaine_id_ec63e3de_fk_maintenance_chaine_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_machine
    ADD CONSTRAINT maintenance_machine_chaine_id_ec63e3de_fk_maintenance_chaine_id FOREIGN KEY (chaine_id) REFERENCES public.maintenance_chaine(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: maintenance_machine maintenance_machine_fournisseur_id_9065494e_fk_maintenan; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_machine
    ADD CONSTRAINT maintenance_machine_fournisseur_id_9065494e_fk_maintenan FOREIGN KEY (fournisseur_id) REFERENCES public.maintenance_fournisseur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: maintenance_machine maintenance_machine_marque_id_d724f20b_fk_maintenance_marque_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_machine
    ADD CONSTRAINT maintenance_machine_marque_id_d724f20b_fk_maintenance_marque_id FOREIGN KEY (marque_id) REFERENCES public.maintenance_marque(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: maintenance_machine maintenance_machine_status_id_f6a44e07_fk_maintenance_status_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_machine
    ADD CONSTRAINT maintenance_machine_status_id_f6a44e07_fk_maintenance_status_id FOREIGN KEY (status_id) REFERENCES public.maintenance_status(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: maintenance_machine maintenance_machine_type_id_b717a9b6_fk_maintenance_type_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_machine
    ADD CONSTRAINT maintenance_machine_type_id_b717a9b6_fk_maintenance_type_id FOREIGN KEY (type_id) REFERENCES public.maintenance_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: maintenance_machinerelation maintenance_machiner_machine_liee_id_59c7d550_fk_maintenan; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_machinerelation
    ADD CONSTRAINT maintenance_machiner_machine_liee_id_59c7d550_fk_maintenan FOREIGN KEY (machine_liee_id) REFERENCES public.maintenance_machine(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: maintenance_machinerelation maintenance_machiner_machine_principale_i_7201a985_fk_maintenan; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_machinerelation
    ADD CONSTRAINT maintenance_machiner_machine_principale_i_7201a985_fk_maintenan FOREIGN KEY (machine_principale_id) REFERENCES public.maintenance_machine(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: maintenance_piecedetachee maintenance_piecedet_emplacement_id_7d650eaa_fk_maintenan; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_piecedetachee
    ADD CONSTRAINT maintenance_piecedet_emplacement_id_7d650eaa_fk_maintenan FOREIGN KEY (emplacement_id) REFERENCES public.maintenance_atelier(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: maintenance_piecedetachee maintenance_piecedet_fournisseur_id_9595b99f_fk_maintenan; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_piecedetachee
    ADD CONSTRAINT maintenance_piecedet_fournisseur_id_9595b99f_fk_maintenan FOREIGN KEY (fournisseur_id) REFERENCES public.maintenance_fournisseur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: maintenance_piecedetachee maintenance_piecedet_modele_id_9a43b09f_fk_maintenan; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.maintenance_piecedetachee
    ADD CONSTRAINT maintenance_piecedet_modele_id_9a43b09f_fk_maintenan FOREIGN KEY (modele_id) REFERENCES public.maintenance_modele(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: utilisateur_utilisateur_groups utilisateur_utilisat_group_id_73c9927f_fk_auth_grou; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utilisateur_utilisateur_groups
    ADD CONSTRAINT utilisateur_utilisat_group_id_73c9927f_fk_auth_grou FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: utilisateur_utilisateur_user_permissions utilisateur_utilisat_permission_id_cadf1c64_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utilisateur_utilisateur_user_permissions
    ADD CONSTRAINT utilisateur_utilisat_permission_id_cadf1c64_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: utilisateur_utilisateur_groups utilisateur_utilisat_utilisateur_id_7f906dff_fk_utilisate; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utilisateur_utilisateur_groups
    ADD CONSTRAINT utilisateur_utilisat_utilisateur_id_7f906dff_fk_utilisate FOREIGN KEY (utilisateur_id) REFERENCES public.utilisateur_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: utilisateur_utilisateur_user_permissions utilisateur_utilisat_utilisateur_id_c5dd5b38_fk_utilisate; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.utilisateur_utilisateur_user_permissions
    ADD CONSTRAINT utilisateur_utilisat_utilisateur_id_c5dd5b38_fk_utilisate FOREIGN KEY (utilisateur_id) REFERENCES public.utilisateur_utilisateur(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

