# Generated by Django 5.1.1 on 2024-09-18 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_marque', models.CharField(max_length=50, unique=True, verbose_name='Marque de la machine')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Date de suppression')),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_modele', models.CharField(max_length=50, unique=True, verbose_name='Nom du modèle')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Date de suppression')),
            ],
        ),
        migrations.CreateModel(
            name='NomMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_machine', models.CharField(max_length=50, unique=True, verbose_name='Nom de la machine')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Date de suppression')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type', models.CharField(max_length=50, unique=True, verbose_name='Type de machine')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Date de suppression')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_serie', models.CharField(max_length=100, unique=True, verbose_name='Numero de serie')),
                ('numero_de_moteur', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de moteur')),
                ('date_mis_en_place', models.DateField(null=True, verbose_name='Date de mise en place')),
                ('status', models.CharField(choices=[('EN_COURS', 'En cours d`utilisation'), ('EN_MAINTENANCE', 'En maintenance'), ('EN_PANNE', 'En panne'), ('HORS_SERVICE', 'Hors service')], default='HORS_SERVICE', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('reference_fabricant', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference fabricant')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Date de suppression')),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fournisseur.fournisseur', verbose_name='Fournisseur')),
            ],
        ),
    ]
