# Generated by Django 5.1.1 on 2024-09-18 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0001_initial'),
        ('piece_detache', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='pieces_detachees',
            field=models.ManyToManyField(blank=True, to='piece_detache.piecedetachee', verbose_name='Pièces détachées'),
        ),
        migrations.AddField(
            model_name='machine',
            name='marque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='machine.marque', verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='machine',
            name='modele',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='machine.modele', verbose_name='Modele'),
        ),
        migrations.AddField(
            model_name='machine',
            name='nom_machine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='machine.nommachine', verbose_name='Nom du machine'),
        ),
        migrations.AddField(
            model_name='machine',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='machine.type', verbose_name='Type'),
        ),
    ]
