# Generated by Django 5.1.1 on 2024-09-26 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_atelier', models.CharField(max_length=50, unique=True, verbose_name='Nom d`atelier')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Date de suppression')),
            ],
        ),
        migrations.CreateModel(
            name='Endroit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_endroit', models.CharField(max_length=50, unique=True, verbose_name='Endroit')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Date de suppression')),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fournisseur', models.CharField(max_length=50, verbose_name='Nom fournisseur')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Téléphone')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Date de suppression')),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_marque', models.CharField(max_length=50, unique=True, verbose_name='Marque de la machine')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Date de suppression')),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_modele', models.CharField(max_length=50, unique=True, verbose_name='Nom du modèle')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Date de suppression')),
            ],
        ),
        migrations.CreateModel(
            name='NomMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_machine', models.CharField(max_length=50, unique=True, verbose_name='Nom de la machine')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Date de suppression')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_responsable', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Téléphone')),
                ('photo', models.ImageField(null=True, upload_to='', verbose_name='Photo')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Date de suppression')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type', models.CharField(max_length=50, unique=True, verbose_name='Type de machine')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Date de suppression')),
            ],
        ),
        migrations.CreateModel(
            name='Chaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_chaine', models.CharField(max_length=50, unique=True, verbose_name='Type de machine')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Date de suppression')),
                ('atelier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.atelier', verbose_name='Chaine')),
            ],
        ),
        migrations.AddField(
            model_name='atelier',
            name='endroit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.endroit', verbose_name='Endroit'),
        ),
        migrations.CreateModel(
            name='PieceDetachee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_piecedetache', models.CharField(max_length=100, verbose_name='Nom de la pièce détachée')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_achat', models.DateField(blank=True, null=True, verbose_name="Date d'achat")),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('reference_fabricant', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference fabricant')),
                ('image', models.ImageField(upload_to='piece_detaches', verbose_name='Image')),
                ('stock_min', models.PositiveIntegerField(verbose_name='Stock minimum')),
                ('stock_max', models.PositiveIntegerField(verbose_name='Stock maximum')),
                ('lot_de_reapprovisionnement', models.PositiveSmallIntegerField(verbose_name='Lot de réapprovisionnement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Date de suppression')),
                ('emplacement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.atelier', verbose_name='Emplacement')),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.fournisseur', verbose_name='Fournisseur')),
                ('modele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.modele', verbose_name='Modele')),
            ],
        ),
        migrations.AddField(
            model_name='atelier',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.responsable', verbose_name='Responsable'),
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_serie', models.CharField(max_length=100, unique=True, verbose_name='Numero de serie')),
                ('numero_de_moteur', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de moteur')),
                ('date_mis_en_place', models.DateField(null=True, verbose_name='Date de mise en place')),
                ('status', models.CharField(choices=[('EN_COURS', 'En cours d`utilisation'), ('EN_MAINTENANCE', 'En maintenance'), ('EN_PANNE', 'En panne'), ('HORS_SERVICE', 'Hors service')], default='HORS_SERVICE', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(null=True, upload_to='machines/', verbose_name='Image')),
                ('reference_fabricant', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference fabricant')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Date de suppression')),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.fournisseur', verbose_name='Fournisseur')),
                ('marque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.marque', verbose_name='Marque')),
                ('modele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.modele', verbose_name='Modele')),
                ('nom_machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.nommachine', verbose_name='Nom du machine')),
                ('pieces_detachees', models.ManyToManyField(blank=True, to='maintenance.piecedetachee', verbose_name='Pièces détachées')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.type', verbose_name='Type')),
            ],
        ),
    ]
