# Generated by Django 5.1.1 on 2024-10-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecedetachee',
            name='date_achat',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'achat"),
        ),
        migrations.AlterField(
            model_name='piecedetachee',
            name='image',
            field=models.ImageField(null=True, upload_to='piece_detaches', verbose_name='Image'),
        ),
    ]
