# Generated by Django 5.1.1 on 2024-10-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_piecedetachee_date_achat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecedetachee',
            name='quantite',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantite'),
        ),
    ]
