# Generated by Django 5.1.1 on 2024-10-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_piecedetachee_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecedetachee',
            name='lot_de_reapprovisionnement',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Lot de réapprovisionnement'),
        ),
        migrations.AlterField(
            model_name='piecedetachee',
            name='stock_max',
            field=models.PositiveIntegerField(null=True, verbose_name='Stock maximum'),
        ),
    ]
