# Generated by Django 5.1.1 on 2024-10-25 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_piecedetachee_lot_de_reapprovisionnement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_status', models.CharField(max_length=50, verbose_name='Nom de status')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Date de suppression')),
            ],
        ),
        migrations.RemoveField(
            model_name='machine',
            name='modele',
        ),
        migrations.AddField(
            model_name='machine',
            name='date_acquisition',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'acquisition"),
        ),
        migrations.AddField(
            model_name='machine',
            name='date_hors_service',
            field=models.DateField(blank=True, null=True, verbose_name='Date de mise hors service'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='image',
            field=models.ImageField(null=True, upload_to='machines/', verbose_name='Image machine'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='nom_machine',
            field=models.CharField(max_length=50, verbose_name='Nom de machine'),
        ),
        migrations.CreateModel(
            name='MachineRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantité de la machine liée')),
                ('machine_liee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liee_a', to='maintenance.machine', verbose_name='Machine liée')),
                ('machine_principale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machines_associees', to='maintenance.machine', verbose_name='Machine principale')),
            ],
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.status', verbose_name='Status'),
        ),
    ]
