# Generated by Django 5.1.1 on 2024-10-28 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_status_remove_machine_modele_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='atelier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.atelier', verbose_name='Atelier'),
        ),
        migrations.AddField(
            model_name='machine',
            name='chaine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.chaine', verbose_name='Chaine'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='machinerelation',
            name='machine_liee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_liee', to='maintenance.machine', verbose_name='Machine liée'),
        ),
        migrations.AlterField(
            model_name='machinerelation',
            name='machine_principale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machine_principale', to='maintenance.machine', verbose_name='Machine principale'),
        ),
    ]
