# Generated by Django 5.1.1 on 2024-11-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_machine_atelier_machine_chaine_alter_machine_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='couleur',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Code couleur statut'),
        ),
    ]
