# Generated by Django 5.1.1 on 2024-11-06 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_status_couleur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='couleur',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code couleur statut'),
        ),
        migrations.CreateModel(
            name='HistoriqueMouvementMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Date de suppression')),
                ('atelier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.atelier', verbose_name='Atelier')),
                ('chaine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.chaine', verbose_name='Chaine')),
                ('machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.machine', verbose_name='Machine')),
            ],
        ),
    ]
