# Generated by Django 5.1.1 on 2024-09-18 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_atelier', models.CharField(max_length=50, unique=True, verbose_name='Nom d`atelier')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Date de suppression')),
            ],
        ),
        migrations.CreateModel(
            name='Endroit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_endroit', models.CharField(max_length=50, unique=True, verbose_name='Endroit')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Date de suppression')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_responsable', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Téléphone')),
                ('photo', models.ImageField(null=True, upload_to='', verbose_name='Photo')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Date de suppression')),
            ],
        ),
        migrations.CreateModel(
            name='Chaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_chaine', models.CharField(max_length=50, unique=True, verbose_name='Type de machine')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True, verbose_name='Date de suppression')),
                ('atelier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atelier.atelier', verbose_name='Chaine')),
            ],
        ),
        migrations.AddField(
            model_name='atelier',
            name='endroit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atelier.endroit', verbose_name='Endroit'),
        ),
        migrations.AddField(
            model_name='atelier',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='atelier.responsable', verbose_name='Responsable'),
        ),
    ]
